[profile.release]
strip = true

[workspace]

members = [
    "server",
    "util",
    "repository",
    "service",
    "graphql",
    "telegram",
    "datasource",
    "coldchain",
    "scheduled",
    "windows",
]