[package]
name = "telegram"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
reqwest = { version = "0.11", features = ["json"] } 
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.66"


[features]
telegram-tests = []