name: Cargo build & test

on:
  push:
    branches:
      - develop
    paths:
      - "backend/**"
  pull_request:
    types: [opened]
    branches:
      - develop
    paths:
      - "backend/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Notify Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      - name: 🔎 Linting...
        run: cargo fmt --all -- --check
      - name: 🧹 Testing...
        run: cargo test --verbose
      - name: 📦 Building...
        run: cargo build --verbose
      - name: Job status
        run: echo "🍏 This job's status is ${{ job.status }}."
